### ISSUE TITLE
Various dual seater bugs/issues

### ISSUE THREAD

**Issue by BonSie** [firewill0/FIR_AWS_SystemDevelopment#1]
**Describe the bug**
Bug 1: Some of the dual seaters have a limited sensor range of 4km on the second seat (F-14s, F15SE, EA-18)
Bug 2: The HMD for the second seat does not work for those where it toggles, gives invalid helmet error. Can be somewhat circumvented by activating it in pilot seat first. (F-14 doesn't have one on either, dunno if intentional)
Bug/request 3: The non F-15 series dual seaters do not have an option to assign weapons to the second seat in the AMS.

**To Reproduce**
Place said planes in editor or via zeus and test

**Expected behavior**
Errr, working HMD and larger sensor ranger for second seat

**Screenshots**
Have recorded quick testing session of needed

**Desktop (please complete the following information):**
SP: CBA, ACE, RHS and all FIR mods
Dedi MP: A lot more

**Comment by firewill0** [comment]
thanks to the report issues, here are some answers for each issue.

1. these aircraft using standard sensor range for the rear seat for a while, will be increase same with pilot's sensor range.
2. currently, toggle HMD option is only supported for the pilot. that means system checks pilot has a proper helmet for support. F-14 was retired before came HMD era, so no option for that.
3. assign weapons to WSO feature is now support F-15E/SE only, but it's also will be support for EA-18G or F/A-18F in future.

**Comment by BonSie** [comment]
Thanks for the response, my clan decided to get all your mods and some are really exited. Expect more feedback because of that.
