### ISSUE TITLE
Missconfig of GBU55 (Fix at the bottom)

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#10]
**Describe the bug**
FIR_GBU55_Navy inherits FIR_GBU32 in Fir_AirWeaponSystem_cfg/Cfgammo.hpp

**To Reproduce**
Equip any GBU55 on any Plane, and try to thow on laser or Dual

**Expected behavior**
GBU55 Laser and Dual Mode Work

**Additional context**
change line 7593 in Fir_AirWeaponSystem_cfg/Cfgammo.hpp from 'class FIR_GBU55_Navy : FIR_GBU32' to 'class FIR_GBU55_Navy : FIR_GBU55' and everything should work

**Comment by firewill0** [comment]
It actually fixed already, but I forgot the repack the PBO when update. so it will be updated soon.
Thank you for your feedback.

**Comment by hschmi-tarent** [comment]
Sorry to bother you, but can you provide a ETA for the Update?

**Comment by firewill0** [comment]
within hour.
