### ISSUE TITLE
F/A18 2020/BETA by TeTeT ECM Jammer not working anymore

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#11]
**Describe the bug**
The ECM Jammer of the F/A 18 by TeTeTe does not work after latest FIR AWS update, that changed ECM

**To Reproduce**
Load F/A 18 beta or 2020 by TeTeTe, with fir aws, try to use the jammer with custom user action 2, or mousewheelmenue

**Expected behavior**
Jammer reacting to custom user action 2 or mousewheelmenue, starting up, logging verbose in vehicle channel, or giving any other feedback.

**Desktop (please complete the following information):**
- Mod list: fir aws, F/A 18 2020 by TeTeTe
- Game type: Tested on hosted and dedi MP

**Additional context**
Maybe you could publish a manual how to use the new ECM-System for non Firewill-Mods.

**Comment by firewill0** [comment]
I'm using this but working with a new ECM system. 
https://steamcommunity.com/sharedfiles/filedetails/?id=743099837

**Comment by HSchmitz1993** [comment]
i was trying with https://steamcommunity.com/sharedfiles/filedetails/?id=2131302796

**Comment by firewill0** [comment]
it's probably working because even vanilla planes(black wasp ii, shikra, etc) working well even I didn't touch anything with them for new ECM system.
