### ISSUE TITLE
F16 Loadout Options

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#12]
**Is your feature request related to a problem? Please describe.**
I m always sad, when flying the F16 in a AirToAir Role, and i cant use 2 of the pylons, because they are bombs only. 
**Describe the solution you'd like**
Make the 2 inner Pylons (tank capable) usable for air to air rockets too, as they should have to most weight capacity, they should be able to handle all weapons in the arsenal

**Comment by firewill0** [comment]
F-16 can't equip ATA missiles on inner pylons IRL unfortunately.
inner pylons equip fuel tanks mostly.

![image](https://user-images.githubusercontent.com/14540382/89412944-e3fd0c00-d762-11ea-85f4-d42eb2c24791.png)

![image](https://user-images.githubusercontent.com/14540382/89413243-76051480-d763-11ea-8333-69ae0fb166a0.png)
