### ISSUE TITLE
BLU 118 JDAM capable

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#13]
**Is your feature request related to a problem? Please describe.**
I am always frustrated when i try to drop a BLU 118 on the enemy, but got to be very close
**Describe the solution you'd like**
Add a GBU-31 BLU-118 variant

**Comment by firewill0** [comment]
there's no GBU-31 w/ BLU-118 variant IRL. BLU-118 integrated to GBU-24, GBU-15, and AGM-130 officially confirmed.
