### ISSUE TITLE
CCIP Indicator for GBU24A Paveway II with BLU-118

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#14]
**Describe the bug**
CCIP Indicator for GBU24A Paveway II with BLU-118 is off

**To Reproduce**
1. F-16 or F15E with GBU24A with BLU-118
2. drop with ccip and no active laser
3. observe splash as compared to intended target
**Expected behavior**
Bomb should drop where aimed

**Desktop (please complete the following information):**
- Mod list: FIR AWS, F15 Eagle, F-16 Falcon
- Game type: Hosted MP

**Comment by firewill0** [comment]
1. each pylon has some "angle", it makes some spread and sadly A3 CCIP system can't adjust for these angle.
2. that's why you have "Laser seeker" so you can drop accurately with laser guide.
