### ISSUE TITLE
Blacklist of classnames does not work

### ISSUE THREAD

**Issue by Tankbuster05** [firewill0/FIR_AWS_SystemDevelopment#15]
**Describe the bug**
Tried to blacklist all variant of skins exept the basic one for the F15 and F16 wich didnt work.

**To Reproduce**
Wrote all classnames of the individual aircraft with skins into the blacklist, but they show up in the build/spawn tab even if written on the blacklist correctly. This work fors for vanilla vehicle to exclude them from being buildable/spawnable but not for the F15/f16 variants.

**Expected behavior**
Blacklisted classnames should not be accesable to build or spawn

**Screenshots**

**Desktop (please complete the following information):**
- Mod list: F15/F16/FIR AWS/Kerberos
- Game type:Dedi MP

**Additional context**
Maybe there could be an option for the addon option to exclude all skins wich would make things easier for mission builders or server hosts.

**Comment by firewill0** [comment]
umm, Kerberos is some kind of server tool?

**Comment by Tankbuster05** [comment]
Kerberos is mp mission type that sets vehicle spawns that can be used by players, that function more or less like the ace arsenal. We wanted to blacklist the jets on the spawn like you can do it with weapons and equipment in the arsenal to reduce the size of the list of vehicles to ease it up on the players.

**Comment by firewill0** [comment]
in that case, I think you could ask to the mission maker.
