### ISSUE TITLE
A-10C,A-10U invisible collision

### ISSUE THREAD

**Issue by Heinz132** [firewill0/FIR_AWS_SystemDevelopment#16]
**Describe the bug**
A-10C,U gets a collision when its on the object (ex. editor-placed runway, aircraft carrier, any flat things on the map)

**To Reproduce**
1-A. place some several airstrip platform at the same level and make a long artificial runway (almyra salt desert will be easy to do this)
1-B. place the aircraft carrier
2. place the A-10C,U on it
3. get on the A-10C,U and take-off

**Expected behavior**
when it accelerate to 15~20km/h, the collision occur, damaging the plane and unable to reach take-off speed

**Screenshots**
i cant find the image upload button

**Desktop (please complete the following information):**
- no mods, only your aircrafts and AWS
- SP (Editor)

**Additional context**
i tried all other aircraft as well, but only A-10C,U get this problem

**Comment by firewill0** [comment]
is A-10"A" having same issue?

**Comment by Heinz132** [comment]
no, only C and U gets it

**Comment by firewill0** [comment]
it's now fixed, will be updated in this week.
