### ISSUE TITLE
FIR AWS GBU-53 Dual mode laser (issue?)

### ISSUE THREAD

**Issue by BLSmilzo** [firewill0/FIR_AWS_SystemDevelopment#17]
**Is your feature request related to a problem? Please describe.**
Scenario: 1 GBU-53 is dropped on a valid TGT in dual-mode.
If there is a laser designator active and a vehicle near the designated area the bomb first uses its radar(/IR?) seeker and then looks for others. That means that if my JTAC is pointing his laser on some infantry and it is also present some kind of vehicle, the bomb will go for the vehicle first ignoring the laser. 

**Describe the solution you'd like**
When dropped in dual mode, the bomb should look first for any lasers, and if none is found go for IR/Radar

**Describe alternatives you've considered**
A workaround to this situation is to drop the bomb manually (GPS with no TGT selected), and the bomb will lock onto the first laser that it sees

**Comment by firewill0** [comment]
some dual-mode capable weapons using a different seeker for terminal guidance. for example, GBU-53 using an infra-red(IR) seeker, not a laser. so it basically heading to the vehicle when you're using dual-mode bombing with I-TGT.

**Comment by BLSmilzo** [comment]
Understood. I would be very happy if the bomb could search for laser first even in dual mode (when dropped in dual and no valid IR tgt is found, it still go for laser). If you think about it, a laser means that someone is telling the bomb that there is a high priority target among others...it would be logical IMHO.
Sorry for bad english, not my motherlanguage.
Thank you
~Tom
