### ISSUE TITLE
F-15SE

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#19]
**Describe the bug**
WSO in F15SE can only switch between 2km and 4km

**To Reproduce**
Spawn a F-15SE. 
Get in on the WSO seat, 
Open Radar
Switch radar scale

**Expected behavior**
Radar going up to 30km, like in the other F-15 variants

**Desktop (please complete the following information):**
- Mod list: Fir AWS, Fir F-15
- Game type: any

**Additional context**
Not sure if its a bug or intended

**Comment by firewill0** [comment]
will be fixed this week.

**Comment by HSchmitz1993** [comment]
hey. dont want to annoy, or pressure. when will you release the change?
