### ISSUE TITLE
REQUIRES ADDON

### ISSUE THREAD

**Issue by DejverinoCZE** [firewill0/FIR_AWS_SystemDevelopment#2]
**Describe the bug**
Hi, I have problem with F-16 Falcon. I installed it yesterday and created map for my Milsim Group. Today it doesnt work and when I tried to edit my map, it says: Required Addon is missing. I didnt change anything !
There are screenshots of that.

**Desktop (please complete the following information):**
- Mod collection: https://steamcommunity.com/sharedfiles/filedetails/?id=1752767878
- Game type: Hosted MP
![20191005112640_1](https://user-images.githubusercontent.com/56190505/66253249-96d89400-e765-11e9-8ec9-92b50e8b4b6e.jpg)
![20191005112650_1](https://user-images.githubusercontent.com/56190505/66253250-96d89400-e765-11e9-9051-0165b4ac7614.jpg)

**Comment by firewill0** [comment]
F-16 has been updated today, and Ramstein birds move to USAFE falcon skin pack.
install this mod and should be fixed.
https://steamcommunity.com/sharedfiles/filedetails/?id=1137922381

**Comment by DejverinoCZE** [comment]
Thank you firewill for help !
