### ISSUE TITLE
i-tgt on F18C/D/F

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#20]
**Describe the bug**
On F18C i-tgt only works with lightening pod in on centerline pylon-
On F18D, and F i-tgt does not work at all.

**To Reproduce**
Spawn F18 variant, 
Equip Loadout,
Start Engine,
Look for I-Tgt in Mouswheelmenu/press custom use action 4

**Expected behavior**
i-Tgt works with or without special equipment in certain slots

**Desktop (please complete the following information):**
- Mod list: fir aws, F18 legacy, project rhino
- Game type: hosted mp

**Additional context**
F18s also dont follow the usual custom control layout for user action 2 for ecm, and useraction 4 for i-tgt

**Comment by firewill0** [comment]
all targeting pods for F/A-18C/D/F are confirmed to work well during the test. can open I-TGT and use it.

F/A-18C/D - LITENINIG on the centerline, LITENING/ATFLIR/Sniper on the left fuselage.
F/A-18F - ATFLIR on the left fuselage(it's only available targeting pod for F/A-18E/F super hornet and Growler)

**Comment by HSchmitz1993** [comment]
thank you for the quick answer, we were able to reproduce your results with C/D, but F is still not working. i got two lasers (one without any description, one atflir) as WSO, but no itgt.
do you have any clues as to why?

**Comment by firewill0** [comment]
if I have the same problem, could be tried for a fix but still, no problem found in my test, so currently no clue.

**Comment by HSchmitz1993** [comment]
thx for yout help though. appreciate your work a lot

**Comment by HSchmitz1993** [comment]
one addition: if you equip the F18C to carry SLAM-ER with a ADLP in the middle pylon, you dont have access to i-tgt anymore. but if you equip litening pod, you cant use CG mode.

**Comment by firewill0** [comment]
in that case, you can equip ATFLIR or Sniper on the left fuselage and equip ADLP on the center.
