### ISSUE TITLE
F15 WSO HMD

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#21]
**Is your feature request related to a problem? Please describe.**
Im only getting a HMD and HUD as WSO in the F15SE when i take control of the Aircraft. 

**Describe the solution you'd like**
I want to have access to at least the HMD all the time as WSO

**Comment by firewill0** [comment]
I guess HMD is linked to the controller who controls the aircraft. might be there's another way to show HMD for gunner or WSO all time, but hud/hmd config is not my best part so probably take many times to find out.
