### ISSUE TITLE
Scalpel not tracking

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#22]
**Describe the bug**
SCALPEL LCDPB does not track a Laser at all, just flies as "dumb" bomb

**To Reproduce**
1.get a plane (we used F18D) with scalpel equiped
2. lase a target
3. drop bomb 30m from laser
**Expected behavior**
Bomb tracks the laser, and hits the intended Target

**Desktop (please complete the following information):**
- Mod list: fir aws, ace, fir f18
- Game type: Hosted MP

**Additional context**
It seems to be the parent class for the scalpel is the vanilla Bo_GBU12_LGB, which has no component for laser tracking for your System.
FIR_AirWeaponsystem_US_cfg/CfgAmmo.hpp:8315

proposed change: change parent class to FIR_GBU12 to just override hit, indirect hit, and indirecthitrange

**Comment by firewill0** [comment]
Bo_GBU12_LGB has a laser component actually because the "ammo_Bomb_LaserGuidedBase" class got a laser and NV component and Bo_GBU12_LGB is inherited from that.
however, scalpel in developing version using FIR_GBU12 for parent class right now(doesn't matter about this.), so eventually will fix.
