### ISSUE TITLE
new I-Tgt POI not working for WSO

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#23]
**Describe the bug**
POI-Function only works for Pilot, not for WSO. as WSO it just says: "tracking mode not activated" 

**To Reproduce**
sit in wso in f15SE or f18D or similar plane
aim camera somewhere
open i-tgt
press poi

**Expected behavior**
i-tgt takes that position as target

**Desktop (please complete the following information):**
- Mod list: fir aws, ace, f15, f18
- Game type:  Hosted MP

**Additional context**
not sure if fixable, but wanted to ask
thx a lot for itgt 2.0. i m still learning
will you do a tutorial for itgt, or update the existing documentation?

**Comment by firewill0** [comment]
it's only supported for the pilot because commands in the script only available for the pilotcamera.
and also currently making tutorials for I-TGT 2.0 for this month.
