### ISSUE TITLE
CBU105 SFW WCMD

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#24]
**Describe the bug**
i remember a year ago when testing the cbu105 would only hit vehicles. as per function. 
now the bomb just dispenses its submunitions, but those submunitions do not track vehicles.

**To Reproduce**
equip a plane with cbu105
drop on area with vehicles in them (did not matter in testing if hot (moved) or not)

**Expected behavior**
pellets track vehicles and impact them with efp

**Desktop (please complete the following information):**
- Mod list: ace, fir aws, f18
- Game type: Hosted MP

**Additional context**
i tried it on cold and hot vehicles, but didnt seem to make any difference. 
any advice?

**Comment by firewill0** [comment]
It's worked because I just did a test right now and worked as well.
it doesn't matter vehicles are cold or hot, just check vehicles in a specific zone, make bomblets, and explode on vehicles.
