### ISSUE TITLE
Incorrect stall speeds on F-18s, possibly all other planes

### ISSUE THREAD

**Issue by FighterAceee** [firewill0/FIR_AWS_SystemDevelopment#25]
The F-18 should stall at around 135knots (250km/h), but the one in the mod stalls at under 135km/h.

Reproducing this should be easy enough, by just flying as slow as possible.

I guess you haven't converted any of the reference flight speeds from knots to km/h because all displayed speeds in Arma3 are in km/h.

**Comment by firewill0** [comment]
it's not related to confusing knots and km, It's actually intended when I start making aircraft mods 6 years ago, a bit more arcade-style. I guess someone already made aka "realistic or DCS like" flight model patch for some of my aircraft but not sure F/A-18 also in there.
