### ISSUE TITLE
Fuel Tank Error

### ISSUE THREAD

**Issue by beno83au** [firewill0/FIR_AWS_SystemDevelopment#26]
**Describe the bug**
When working with the "FIR_F18C" this error is logged in the .rpt:
`unable to create weapon for missile 'FIR_FA18_Fueltank_P_1rnd_M', check config entry'pylonWeapon'`

**To Reproduce**
Run ArmA 3 with F/A-18 and AWS mods. Place a "FIR_F18C" in the editor and run the mission, then check .rpt. The error is also logged in .rpt when you add the fuel tank to the aircraft in the editor.

**Desktop (please complete the following information):**
- Mod list:
    - F/A-18 Hornet
    - AWS

- Game type: Editor SP

**Additional context**
The fuel tank still spawns on the aircraft.

**Comment by firewill0** [comment]
this error can be ignored actually.
