### ISSUE TITLE
Missing/Incorrectly Linked Sound File

### ISSUE THREAD

**Issue by beno83au** [firewill0/FIR_AWS_SystemDevelopment#27]
**Describe the bug**
Error logged in the .rpt stating a sound was not found:
`Sound: Error: File: fir_fa18\sounds\exterior\16_midthrottle_forsage.wss not found !!!`

**To Reproduce**
Run ArmA 3 with F/A-18 and AWS mods. Place a "FIR_F18C" in the editor and run the mission, then check .rpt.

**Expected behavior**
Sound file to be linked correctly.

**Desktop (please complete the following information):**
- Mod list:
    - F/A-18 Hornet
    - AWS
- Game type: Editor SP

**Comment by firewill0** [comment]
file missing in a sound folder so will be fixed.
