### ISSUE TITLE
CBU105 issue (again)

### ISSUE THREAD

**Issue by HSchmitz1993** [firewill0/FIR_AWS_SystemDevelopment#28]
**Describe the bug**
CBU105 not Sensor-Fuzing, while CBU97 is

**To Reproduce**
Drop one CBU97, and a CBU105 on a target Rich environment 

**Additional context**
I am really sorry to bother you again, but i got a strange bug, that the CBU105 is just splattering all over the place, but the cbu97 works, and only hits vehicles. and i really like the cbu105, and would like it to work again. do you have any ideas, what i could be doing wrong?

**Comment by firewill0** [comment]
well in that case CBU105 will remove, unfortunately...




just joke. I'll test it is work.

**Comment by firewill0** [comment]
yet again, CBU105 worked for me and vehicles have been destroyed at the target location.
