### ISSUE TITLE
Session Lost - Verifying PBO failed

### ISSUE THREAD

**Issue by Choelstad91** [firewill0/FIR_AWS_SystemDevelopment#29]
As of yesterday I've had this issue, "Session lost - Verifying PBO failed: @FIR_AWS(AirWeaponSystem)\addons\fir_airweaponsystem_us_cfg.pbo

I have tried Repairing the mod, verifying game files, unsubbing and resubbing the mod, same for my mod list, I've reinstalled arma, I've even tried using someone elses pbo and key file, I've deleted the PBO and bisign file and repaired the mod, I've tried deleting all my mods and downloading FROM SERVER LIST no luck.

Server is updated, 3 other players are able to play. The mod was updated on the 15th of this month (2 days before i had issues) and i played both on the 15th and the 16th. When i tried to log in on the 17th, I had this issue.

My buddy(who rents the server) saw there was an update and updated it(FIR) but it did not fix it.

Any of the PBO problems i seem to find on google is about the 1.90 update 2 years ago.... 

Mods used on the server;
Advanced Combat Environment 3.13.5
FIR AIRWEAPONSYSTEM
A-10 Warthog Series
F-16 Fighting Falcon
F-14D Tomcat
Project Legacy - F/A-18 Hornet
Achilles
Community Base Addons v3.15.2
Napf Island v1.2
Sling Load Rigging
CUP Terrains ACE Compatibility 1.12.0
CUP Terrains - Maps 1.16.0
CUP Terrains - Core 1.16.1
@RHS ACE compatible files
RHS: Serbian Armed Forces
RHS: United States Forces
RHS: GREF
RHS: Armed Forced of the Russian Federation

**Comment by firewill0** [comment]
signature check system says valid and problem not found, even check with workshop version says the same thing. maybe need to test with a signature checked server.

**Comment by firewill0** [comment]
Well, I tested Dedi server with signature checked(v2), but it's working properly. are your friends have the same issue or just only you?

**Comment by Choelstad91** [comment]
Im sorry, i did not notice the replies. So im sorry for wasting your time, but turns out I had the newest version, the server had .56, when my buddy updated the server it must not have updated to .57, that is fixed now and all is good. Sorry about that, I went through all possible troubleshooting because I was certain the server was up to date lol
