### ISSUE TITLE
AV-8B Plus Camera issue

### ISSUE THREAD

**Issue by Bruce15thMEU** [firewill0/FIR_AWS_SystemDevelopment#3]
When operating the AV8B Plus on a MP server the targeting pod camera randomly locks at a certain zoom level, preventing you from zooming all the way out. This has occurred on multiple occasions with different clients and on different servers but is not reproducible that we have found. The only solution we have found is to get a different aircraft. Repairing the aircraft and changing the pod via AWS load out does not help.

**Comment by firewill0** [comment]
I'm aware this issue because same few reports heard before. problem is, still can't reproduce this problem in my case.
I'm really sorry for can't fixing right now.

**Comment by Bruce15thMEU** [comment]
We only fly the AV-8B Plus model, VMA-214 models to be precise.
