### ISSUE TITLE
AN/ALQ-99 Bug

### ISSUE THREAD

**Issue by beno83au** [firewill0/FIR_AWS_SystemDevelopment#30]
**Describe the bug**
Two of the blades on the front of the AN/ALQ-99 on the EA-18G appear to snap their rotation by 90 degrees every half rotation of the component.

**To Reproduce**
Add an AN/ALQ-99 to an EA-18G and observer the rotation.

**Expected behavior**
That they don't rotate.

**Screenshots**
Video here: https://youtu.be/nt47JfYl1l4

**Desktop (please complete the following information):**
- Mod list: EA-18G, AWS
- Game type: Any

**Comment by firewill0** [comment]
it because only rotates 180 degrees, back to the start and loop so looks like that.

**Comment by beno83au** [comment]
Ok, no worries. Sorry for the trouble :)

Sent from Yahoo Mail on Android 
 
  On Wed, 24 Feb 2021 at 13:50, Firewill<notifications@github.com> wrote:   


it because only rotates 180 degrees, back to the start and loop so looks like that.
