### ISSUE TITLE
Possible Incorrect "missileLockMaxSpeed"

### ISSUE THREAD

**Issue by beno83au** [firewill0/FIR_AWS_SystemDevelopment#34]
**Describe the bug**
Under _configfile >> "CfgAmmo"_ ammunition classes appear to have the incorrect value for _"missileLockMaxSpeed"_. They look to be defined as km/h, when the config value is measured in m/s:
[https://community.bistudio.com/wiki/Arma_3:_Targeting_config_reference#missileLockMaxSpeed]

**To Reproduce**
Check any FIR ammo configs for _"missileLockMaxSpeed"_.

**Expected behavior**
That values be defined as described in the config reference.

**Desktop (please complete the following information):**
- Mod list: FIR_AWS, FIR F-15
- Game type: Editor

**Additional context**
Just happened to notice it when preparing to write a script to grab ammo config values on the fly. I learnt that vanilla Arma 3 values for _"missileLockMaxSpeed"_ were defined in m/s, and when grabbing the values from FIR weapons they returned much larger results than expected.

**Comment by firewill0** [comment]
thanks the heads up, will adjust in next update.
