### ISSUE TITLE
POI Markers not disappearing from Map

### ISSUE THREAD

**Issue by JeroenV1982** [firewill0/FIR_AWS_SystemDevelopment#35]
**Describe the bug**
POI Markers not disappearing from Map after deleting them in I-TGT.

**To Reproduce**
Place a POI Marker, delete the marker in I-TGT and look at the MAP

**Expected behavior**
N/A

**Screenshots**
N/A

**Desktop (please complete the following information):**
- Mod list: FIR AWS
- Game type: MP

**Additional context**
N/A

**Comment by firewill0** [comment]
it's deleted in my test. is anything more detail?

**Comment by JeroenVBH** [comment]
![Fir1](https://user-images.githubusercontent.com/17387175/114691517-0db9fa00-9d18-11eb-898f-64b31834b658.png)
![Fir2](https://user-images.githubusercontent.com/17387175/114691527-10b4ea80-9d18-11eb-820d-9361fe31c95d.png)
![Fir3](https://user-images.githubusercontent.com/17387175/114691540-13174480-9d18-11eb-8cb8-0820bb937dbf.png)

Please have a look at my screenshots. As you can see my list is empty after deleting them but they still appear on the map. Also after going above 10, the count starts at 0 and they won't show up on the map anymore.

**Comment by firewill0** [comment]
I've tested with Dedicated server, but still worked for me.
If I have a same problem, might be find what is problem.
example 1 : A-164 Wipeout
![20210416130415_1](https://user-images.githubusercontent.com/14540382/114970278-1bf14d00-9eb5-11eb-8c4c-b453415efe82.jpg)
![20210416130421_1](https://user-images.githubusercontent.com/14540382/114970309-2875a580-9eb5-11eb-8c69-41ac97945275.jpg)
![20210416130423_1](https://user-images.githubusercontent.com/14540382/114970319-2b709600-9eb5-11eb-8e8b-e38d30e4c1d2.jpg)
![20210416130424_1](https://user-images.githubusercontent.com/14540382/114970327-2d3a5980-9eb5-11eb-8ca8-3193424f3c7c.jpg)
example 2 : F-16C
![20210416130829_1](https://user-images.githubusercontent.com/14540382/114970341-36c3c180-9eb5-11eb-95f6-fc63792b7192.jpg)
![20210416130831_1](https://user-images.githubusercontent.com/14540382/114970349-39261b80-9eb5-11eb-9af7-b0602aaea4d4.jpg)
![20210416130832_1](https://user-images.githubusercontent.com/14540382/114970353-3b887580-9eb5-11eb-8e51-cd20cd868f83.jpg)
![20210416130835_1](https://user-images.githubusercontent.com/14540382/114970360-3d523900-9eb5-11eb-9798-ce19dc1ea43c.jpg)

**Comment by JeroenVBH** [comment]
Mmm strange your not having the same issue. And what if you go above 10 markers, destroy the plane and take a new plane, do you still see the old markers like I did from the old plane?

I have a request for your mod; Could you make a warning when friendlies are near the POI like this?:
![POI_Friendly](https://user-images.githubusercontent.com/17387175/114981677-a6728600-9e8e-11eb-8f91-040e3c6677b3.png)

**Comment by firewill0** [comment]
remove marker when aircraft is dead is still work in progress, and your request is possible, but for reduce script load, probably gonna make some button for searching friendlies near TGT point.

**Comment by JeroenVBH** [comment]
That would be very helpful, thanks for your awesome mods!

**Comment by JeroenV1982** [comment]
Have you tried to place markers, then crash yourself and take the same plane? The I-TGT list will then be empty but the map would still shows the old markers.

**Comment by firewill0** [comment]
yes I've just tested and marker is now removed after aircraft is crashed/destroyed.

**Comment by JeroenV1982** [comment]
Super thank you! Will ask the Server owner to update ASAP!
