### ISSUE TITLE
CBU-105 SFW WCMD Deployment changing to HE cluster mid-air

### ISSUE THREAD

**Issue by Hornet221** [firewill0/FIR_AWS_SystemDevelopment#36]
**Describe the bug**
When deploying the CBU-105 SFW cluster munitions (Both using I-TGT and without) it seems that at higher altitudes and higher angles of attack on the target, cause the SFW to malfunction, and instead of deploying the parachutes/munitions, it bursts into a vanilla style cluster munition, leaving behind HE UXO and not destroying targets as intended.

**To Reproduce**
Drop CBU-105 SFW weapons from high altitude, or a high angle of attack on target, Low drops will make the system work correctly (Level Flight, approx 2500M Max) 

**Expected behavior**
The bomb would unpack, deploying the sub munitions with parachutes/pucks/rockets as intended, with the pucks locking and destroying any vehicles in the effective area of the CBU 

**Screenshots**
See below
![20210602162626_1](https://user-images.githubusercontent.com/85514747/121069196-1f25fc80-c7c5-11eb-8657-7ef4964f36ff.jpg) Incorrect Deployment 
(Dropped from 3500-4000M at approx -20' nose down)
![20210602162137_1](https://user-images.githubusercontent.com/85514747/121069211-23521a00-c7c5-11eb-97cc-682a7322a33e.jpg) 
UXO
![20210602162852_1](https://user-images.githubusercontent.com/85514747/121069316-3f55bb80-c7c5-11eb-85d1-954593609aa7.jpg) 
Correct Deployment

**Desktop (please complete the following information):**
- Mod list: Fir AWS, F-16 (No other mods)
- Game type: all

**Additional context**
Confusingly enough, the CBU-97 (The non GPS guided counterpart) Can be dropped from any angle and direction, and will deploy correctly every time.

**Comment by firewill0** [comment]
CBU-105 got CBU-103 parent class unknown reason. it's will be fixed.
