### ISSUE TITLE
How does ECM system work after v3.52?

### ISSUE THREAD

**Issue by AdamAb44** [firewill0/FIR_AWS_SystemDevelopment#39]
**Is your feature request related to a problem? Please describe.**
ECM system functionality changed with v3.52. Apart from "A new ECM system uses ECM capability in aircraft to determine the success of jamming or not.", there are no more details.

**Describe the solution you'd like**
A clear and concise description of how the new ECM system works.

**Describe alternatives you've considered**
Revert to previous functionality of ECM system.

**Additional context**
N/A

**Comment by firewill0** [comment]
Previous ECM was too OP against radar guided missile because can jammed 100%. a new ECM system is based on ECM capability "in config" so no longer 100% to jammed.
just new system is no more perfect jamming for gaming balance.

**Comment by AdamAb44** [comment]
I agree it was too OP, no doubt.

What I would like to have though is some information on how exactly it is working now?
I suppose that in real life, there are some statistics on how successful the ECM is in jamming → could you tell us the numbers in config and so what are the chances for ECM to jam the missile?

Also, previously some info in chat was shown when turning the ECM on and when it turned off. Would it be possible to do the same with the new ECM? I.e. the pilot should know that the ECM is on and that it switched off, otherwise there is no chance to recognize this. Maybe some timer (say each 5 seconds it would tell in the chat that there is xx seconds remaining until the ECM turnes off) would be very nice and handy.

**Comment by AdamAb44** [comment]
So, could you please provide these details?

**Comment by firewill0** [comment]
I think.. just leave some kind of "technical secret", but if you want to check values, you can use the config viewer in A3 and find "AWS_ECM_STAT" in each aircraft and ECM pod
