### ISSUE TITLE
Dumb fire rocket launchers have too low dispersion

### ISSUE THREAD

**Issue by Freddo3000** [firewill0/FIR_AWS_SystemDevelopment#4]
**Describe the bug**
Checking `FIR_RKT_Base`, `FIR_RKT_Launcher` and all inheriting classes they all use the default Dispersion value of 0.002 which gives near pinpoint accuracy. Same goes for all firemodes as well.

Comparing this value with Vanilla's 0.015 on Hydra 70's or CUP FFAR's 0.025 it would appear that 0.002 is far too accurate.

**To Reproduce**
`getNumber (configfile >> "CfgWeapons" >> "FIR_RKT_Launcher" >> "dispersion")`,
`getNumber (configfile >> "CfgWeapons" >> "FIR_RKT_Launcher" >> "Burst" >> "dispersion")`
or check using the Config Viewer

**Expected behavior**
Expected dumb fire rockets to have similar dispersion to Vanilla.

**Desktop (please complete the following information):**
- Mod list: AWS, FA-18, F-14, F-15
- Game type: Config issue

**Comment by firewill0** [comment]
actually, it is intended.

**Comment by Freddo3000** [comment]
Ok, may I ask why?

**Comment by firewill0** [comment]
my taste. there is an important reason more than this?

**Comment by Freddo3000** [comment]
Well it is your mod, so that is reason enough.
