### ISSUE TITLE
Project Tornado - First Person Wing Bug

### ISSUE THREAD

**Issue by Nomas-X** [firewill0/FIR_AWS_SystemDevelopment#44]
**Describe the bug**
The wings of all variants of the Tornado are not rendered correctly in the first person when you look at your wings.

**To Reproduce**
Spawn a Tornado and get in it and look at the wings after the cockpit closes.
[The wings look normal when landed and the cockpit is open]

**Expected behavior**
I expected to be able to see the wing correctly rendered without the visual bug.

**Screenshots**
[In Air](https://cdn.discordapp.com/attachments/547250110359142402/928597749501394984/20220106132450_1.jpg)
[On Ground with Cockpit Closed](https://cdn.discordapp.com/attachments/547250110359142402/928597749245571072/20220106132723_1.jpg)
[On Ground with Cockpit Open](https://cdn.discordapp.com/attachments/547250110359142402/928597748935188520/20220106132719_1.jpg)

**Desktop (please complete the following information):**
- Mod list: **[Project Tornado](https://steamcommunity.com/sharedfiles/filedetails/?id=2499043863)** + **[FIR AWS(AirWeaponSystem)](https://steamcommunity.com/workshop/filedetails/?id=366425329)** OR **[FIREWILL Aviation Pack (Complete)](https://steamcommunity.com/workshop/filedetails/?id=1381545544)**
- Game type: Happens in all environments SP, MP, and Dedicated.

**Additional context**
This problem happens both in the independent mod **[Project Tornado](https://steamcommunity.com/sharedfiles/filedetails/?id=2499043863)** and **[FIREWILL Aviation Pack (Complete)](https://steamcommunity.com/workshop/filedetails/?id=1381545544)**

**Comment by firewill0** [comment]
looks like glass of canopy problem. thanks for the heads up, I'll fix it.
