### ISSUE TITLE
A10C gau 8 sight not calibrated

### ISSUE THREAD

**Issue by kraviso** [firewill0/FIR_AWS_SystemDevelopment#48]
**Describe the bug**
A gau 8 sight in a10c is not calibrated. To hit the target you need to aim a lot higher then sight.

**To Reproduce**
Spawn a10c and try to hit a ground unit from 1500 meters or more.

**Expected behavior**
A gau 8 crosshair should be auto adjusted.

**Screenshots**
.

**Desktop (please complete the following information):**
- Mod list: Firewill AWS
- Game type: SP

**Additional context**
.

**Comment by firewill0** [comment]
crosshair is actually adjusted with A3 CCIP feature, but not sure how many "drop" we need because it's automatically calculated by game engine.

**Comment by kraviso** [comment]
For hydra rockets CCIP is accurate, but in gau 8 bullets hit lower then CCIP is showing.

**Comment by kraviso** [comment]
I forgot to say that I use -10-tastic - Firewill - A-10 & GAU-8 Sound Overhaul mod

**Comment by kraviso** [comment]
https://user-images.githubusercontent.com/98544946/151666795-3d83cc83-d1aa-4660-86cf-f8a6b89b307a.mp4

**Comment by firewill0** [comment]
So in that case there is nothing I can do because you are using additional overhaul mod, it may changed config value about weapon and ammo, not just only sound.
the original gau-8 in FIR AWS is designed working CCIP properly. so I think you should ask to author of that overhaul mod, not me.
