### ISSUE TITLE
GBU-39 SDB for A-10C

### ISSUE THREAD

**Issue by CrunchRiff** [firewill0/FIR_AWS_SystemDevelopment#49]
**Is your feature request related to a problem? Please describe.**
The GBU-39/B SDB is being integrated into the A-10C (along with the already featured Scorpion helmets) per USAF news releases in 2019. The BRU-61/A ejector rack with 4x GBU-39/Bs fitted nominally weighs just under 1500 lbs. That should make it compatible with pylons 3, 4, 8, and 9.

**Describe the solution you'd like**
Please add compatibility for A-10C to fit the GBU-39 SDB x4 to pylons 3, 4, 8, and 9.

Also, if possible, please add compatibility with the vanilla A-164 Wipeout on its pylons 3, 4, 7, and 8. (Same positions - no centerline pylon/number for vanilla.)

**Describe alternatives you've considered**
The USAF Mod's A-10 already has compatibility with their GBU-39 x4 (on all 11 pylons, humorously), but there are several things I prefer about the Firewill A-10C. Also I occasionally use the Vanilla wipeout with AWS, so it would be a nice inclusion there as well.

**Additional context**
That should be it. Thanks for the great mods!

**Comment by firewill0** [comment]
Thanks for info! I didn't know GBU-39 is integrated to A-10C, so it would be done soon as possible. of course, I'll take a look integrate SDB to A-164 too.
