### ISSUE TITLE
Start Screen Tiles/Buttons Missing

### ISSUE THREAD

**Issue by kMaN175** [firewill0/FIR_AWS_SystemDevelopment#51]
I think your Sep 12 update broke the Start Screen Tiles/Buttons.

Launch Arma with only the FIR AWS mod loaded.

Screenshot:
https://imgur.com/BABUEH3

YouTube:
https://youtu.be/XnIMFYl0uyw

Desktop (please complete the following information):
- Mod list: Only Fir AWS
- Game type: Any

**Comment by firewill0** [comment]
Removing center icons intentional since new update(because for new cutscene) so not a broke something.

**Comment by kMaN175** [comment]
Oh, okay. No worries. Thank you.
