### ISSUE TITLE
No option to open GPS I-TGT in F18 and F14 (All variants)

### ISSUE THREAD

**Issue by Armybarmy101** [firewill0/FIR_AWS_SystemDevelopment#58]
**Describe the bug**
Hi there, I cannot open the I-TGT system. I am sure that last week it worked in the F14. But now we cannot open it for 2 seater planes. Maybe this is a bug or we do something wrong? What we expect to happen is that the copilot/weapons officer can have access to the I-TGT system while the pilot flies. 

Only mod is ACE and your own. This is on hosted/dedicated MP and I replicated the issue on SP. 

UPDATE - Only affecting the dual seat variants. Single seater is fine. Shame its not working in the two seater. Can this be fixed please? 

Thanks.  

**To Reproduce**
Try opening it.

**Comment by firewill0** [comment]
There's nothing restriction code in I-TGT about pilot or gunner so maybe something other problem not in AWS/I-TGT, especially you said it worked in last week.

**Comment by Armybarmy101** [comment]
Hello,

Ok thanks for reply. Its still not working so for now I guess we will have to use single seater planes or other mod packs. Ideally the gunner seat should only have access to it anyway on the two seater variants. 

Thanks again.
