### ISSUE TITLE
Camera slew for copilot/weapons officer goes off target

### ISSUE THREAD

**Issue by Armybarmy101** [firewill0/FIR_AWS_SystemDevelopment#59]
**Describe the bug**

When using the camera to laser guide - it sometimes goes way off and resets or looks at the back of the aircraft meaning you have to move it back on to target again. Also - when you release camera and say, look at map or look in your cockpit - this also continues to move the camera so it does not hold in the same place. 

**To Reproduce**
Boot up and have a go in coop flight. 

**Expected behavior**

However while in a single pilot plane - the camera does not behave this way. The pilot can use the camera, and when he releases it and looks at map or moves mouse around to fly - the camera still does not move. So the request here is that can the copilot/WO have the same function of the camera please? This is what is expected. 

**Desktop (please complete the following information):**
ACE, MP mode. 

Thank you very much for your hard work.

**Comment by firewill0** [comment]
Pilot camera =/= gunner camera in game engine. so there's nothing I can do. 
only I can make gunner camera is locked when **zoomed in** , can't be make like pilot camera.

**Comment by Armybarmy101** [comment]
Hi,

Thanks for the reply. Sorry I do not understand what you mean. The camera goes off and looks somewhere else on its own for the gunner. It is VERY hard to use it on operations and frustrating for the gunner to use. I suppose for now, we will just use other mod pack/single planes from your pack. 

Thanks again.

**Comment by firewill0** [comment]
Gunner camera uses different algorithm, so can't be make exactly same to pilot camera.
only I can make camera can be lock the axis when player zoomed in, and it's might be lost the track when player doing something other. It's can't do anything from me, just A3 engine does.
