### ISSUE TITLE
ams-lite removes gun and laser designator on Xi'an vtol

### ISSUE THREAD

**Issue by 0ptus** [firewill0/FIR_AWS_SystemDevelopment#7]
**Describe the bug**
When using enablefunction to add ams-lite on the Y-32 Xi'an vtol from Apex and applying a new loadout, the main cannon and laser designator usually controlled by the gunner are no longer available. 

**To Reproduce**
Spawn any Xi'an variant, add the enablefunction to the init (I used the complete "[this,true,true,true,true] call fir_fnc_aws_enablefunction;"). Spawn a missile carrier.
Start the mission as gunner or pilot and select any loadout through ams-lite. Giving the gunner control of any of the pylons doesn't make a difference.
On Applying the Loadout, the gunners cannon and laser designator vanish from weapon selection and can no longer be used.

**Expected behavior**
Pylon Weapons should change while the weapons that are not changeable through the pylon system remain useable, as with other planes and helicopters (I tested ams-lite on the blackfoot). This problem does not occur when using the pylon settings in the editor.

**Desktop:**
- Mod list: FIR AWS(AirWeaponSystem) (Steam)
- Game type: SP out of Eden Editor, Hosted MP

**Comment by firewill0** [comment]
Hi, thank you for feedback.
I've found what is the problem, currently fixing and will be updated when test completed.

Thank you.

**Comment by 0ptus** [comment]
Happy to help. Your Mods are very inspiring by the way, found the bug while trying to create a customized version of the Xi'an.
