### ISSUE TITLE
F/A 18 - AI not using tailhook

### ISSUE THREAD

**Issue by ERazgriz** [firewill0/FIR_AWS_SystemDevelopment#8]
**Describe the bug**
AI is able to land on carriers, but it doesn't use tailhooks. I don't know if it isn't programmed to or it's a bug.

**To Reproduce**
Spawn Freedom Carrier
Spawn F/A 18 in the air with a pilot in about 3 kms distant from the carrier
Put a "LAND" waypoint in the Carrier's Yellow square box in the editor (map view)
The plane will pass the carrier, make a return and land. It only won't use the tailhook.

**Expected behavior**
The AI uses the tailhook and catch the cable

**Screenshots**
![image](https://user-images.githubusercontent.com/64353565/80303370-520a5e00-8786-11ea-8782-a69edfd76f87.png)

![image](https://user-images.githubusercontent.com/64353565/80303493-fbe9ea80-8786-11ea-85c2-00e735e2f476.png)

**Desktop (please complete the following information):**
- Mod list: All F/A 18 versions (Hornet, Rhino and Growler) and its dependencies
- Game type: Editor, SP

**Additional context**
The problem might be solved if the plane lowers the tailhook together with the landing gear like the Black Wasp from the vanilla game
The problem also applies for the F-14, but a bit worse since the F-14 can't stop fast enough
F/A 18 Don't clear runway also.

**Comment by firewill0** [comment]
I guess my aircraft didn't have some event handler for AI using tailhook when landing on aircraft. however, that event handler is designed for F/A-181 Black Wasp II, so need some tune for can be applied to other aircraft, and probably take some time.

here is using some commands in Land waypoint is an alternative way, and can use it right now.
F-14, and all F/A-18(Legacy hornet to Growler) supported.
![20200426214944_1](https://user-images.githubusercontent.com/14540382/80308098-f54f8780-8807-11ea-9262-185b637b00d6.jpg)
![20200426214940_1](https://user-images.githubusercontent.com/14540382/80308111-fd0f2c00-8807-11ea-840d-17cbc32410f7.jpg)
![20200426214902_1](https://user-images.githubusercontent.com/14540382/80308118-06989400-8808-11ea-8a87-25dfe555098e.jpg)

**Comment by ERazgriz** [comment]
I was testing it to use in a Warlords missions (doesn't accept scripts in vehicles), but thank you! That will me useful too. If I can help with that in any way, just say a word o7
