### ISSUE TITLE
ACE full repair not working, can't do Advanced Damage from Achilles

### ISSUE THREAD

**Issue by BenFromTTG1249** [firewill0/FIR_AWS_SystemDevelopment#9]
**Describe the bug**
The ACE full repair interaction doesn't show up, and you can't set the advanced damage on planes using the Achilles mod. Tested on Harrier and EA-18G

**To Reproduce**

1. Install the Harrier and EA-18G, as well as Achilles
2. Load into a Zeus mission with the Addon Options>ACE Logistics>Full Repair Locations set to Anywhere
3. Try to repair one of the planes with a toolkit

**Expected behavior**
Expected a Repair>Full Repair option in ace option

**Screenshots**
https://imgur.com/a/eRk1agn

**Desktop (please complete the following information):**
- Mod list: http://www.mediafire.com/file/9xbma62bl9h55ws/Arma_3_Preset_Carrier_Sim.html/file
- Game type: SP, Hosted MP

**Additional context**
TeTeT's F/A-18 works, as well as Laroche's F-35C.

**Comment by firewill0** [comment]
Unfortunately, my aircraft are not designed for use together with ACE nor Achilles.
So, you can repair and rearm with AMS and it's Nimitz supported(that means you can open AMS dialog when your aircraft on flight-deck) and use AMS is recommended.

**Comment by BenFromTTG1249** [comment]
Do you happen to know of any compat mods that add Ace compatibility? Or how to make it myself?

**Comment by BenFromTTG1249** [comment]
From talking further with the ACE team, there seems to be a problem with the hitpoints. Not sure if they are configured or not.

**Comment by firewill0** [comment]
except for F-16, my aircraft still didn't define hitpoints. maybe that's could be an issue. 
hitpoint system is will be updated but that's not a top-priority thing so probably take some time.

**Comment by BenFromTTG1249** [comment]
If you know of a tutorial on how to do it I'd be happy to help.

**Comment by firewill0** [comment]
It's only what I have to do, unfortunately.
